package org.jesperancinha.enterprise.staco.cloud.domain

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConvertedEnum
import org.jesperancinha.enterprise.staco.common.domain.CurrencyType
import org.jesperancinha.enterprise.staco.common.domain.IStaCo
import org.jesperancinha.enterprise.staco.common.domain.ObjectType
import org.jesperancinha.enterprise.staco.common.dto.Description
import org.jesperancinha.enterprise.staco.common.dto.StaCoDto

@DynamoDBTable(tableName = "staco")
data class StaCo(
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    val dynId: String? = null,

    @DynamoDBAttribute(attributeName = "id")
    override val stacoId: String? = null,

    @DynamoDBAttribute
    override val description: String?,

    @DynamoDBAttribute
    override var year: String?,

    @DynamoDBAttribute
    override var value: String?,

    @DynamoDBTypeConvertedEnum
    @DynamoDBAttribute
    override var currency: CurrencyType?,

    @DynamoDBTypeConvertedEnum
    @DynamoDBAttribute
    override var type: ObjectType,

    @DynamoDBAttribute
    override val diameterMM: String?,

    @DynamoDBAttribute
    override val internalDiameterMM: String?,

    @DynamoDBAttribute
    override val heightMM: String?,

    @DynamoDBAttribute
    override val widthMM: String?,
) : IStaCo


internal val StaCo.toDto: StaCoDto
    get() = StaCoDto(
        null,
        Description(description),
        year,
        value,
        currency,
        type,
        diameterMM,
        internalDiameterMM,
        heightMM,
        widthMM
    )

internal val StaCoDto.toData: StaCo
    get() = StaCo(
        description = description.toString(),
        year = year,
        value = value,
        currency = currency,
        type = type,
        diameterMM = diameterMM,
        internalDiameterMM = internalDiameterMM,
        heightMM = heightMM,
        widthMM = widthMM
    )
