package org.jesperancinha.enterprise.staco.ls.domain

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBDocument
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable
import org.jesperancinha.enterprise.staco.common.domain.CurrencyEnum
import org.jesperancinha.enterprise.staco.common.domain.IStaCo
import org.jesperancinha.enterprise.staco.common.dto.StaCoDto
import javax.persistence.Entity
import javax.persistence.Id
import javax.persistence.Table

@DynamoDBTable(tableName= "staco")
data class StaCo(
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    override val id: Long? = null,

    @DynamoDBAttribute
    override val description: String?,

    @DynamoDBAttribute
    override var year: String?,

    @DynamoDBAttribute
    override var value: String?,

    @DynamoDBAttribute
    override var currency: CurrencyEnum?,

    @DynamoDBAttribute
    override val diameterMM: String?,

    @DynamoDBAttribute
    override val internalDiameterMM: String?,
    
    @DynamoDBAttribute
    override val heightMM: String?,

    @DynamoDBAttribute
    override val widthMM: String?,
) : IStaCo


internal val StaCo.toDto: StaCoDto
    get() = StaCoDto(
        description,
        year,
        value,
        currency,
        diameterMM,
        internalDiameterMM,
        heightMM,
        widthMM
    )

internal val StaCoDto.toData: StaCo
    get() = StaCo(
        description = description,
        year = year,
        value = value,
        currency = currency,
        diameterMM = diameterMM,
        internalDiameterMM = internalDiameterMM,
        heightMM = heightMM,
        widthMM = widthMM
    )
